In [ ]:
import cv2
import numpy as np

def get_contour_areas(contours):
    # returns the areas of all contours as list
    all_areas = []
    for cnt in contours:
        area = cv2.contourArea(cnt)
        all_areas.append(area)
    return all_areas

image = cv2.imread('images/tablet.jpg')
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
edged = cv2.Canny(gray, 30, 200)
# Use a copy of your image e.g. edged.copy(), since findContours alters the image
_, contours, hierarchy = cv2.findContours(edged, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
print("Number of Contours found = " + str(len(contours)))

# Sort contours large to small
sorted_contours = sorted(contours, key=cv2.contourArea, reverse=True)
print (get_contour_areas(sorted_contours))
print (sorted_contours[2])

cv2.drawContours(image, sorted_contours, 0, (0,255,0), 3)

cv2.imshow('Contours', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

Number of Contours found = 55
[300212.0, 418.5, 167.5, 150.0, 133.0, 127.5, 122.5, 97.5, 82.5, 59.0, 31.0, 28.5, 25.5, 21.5, 20.5, 18.5, 14.0, 11.0, 11.0, 10.0, 9.5, 6.0, 4.0, 2.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[[[193 713]]

 [[191 715]]

 [[191 723]]

 [[192 723]]

 [[193 724]]

 [[194 724]]

 [[196 722]]

 [[199 722]]

 [[200 723]]

 [[201 722]]

 [[202 722]]

 [[203 721]]

 [[205 723]]

 [[208 723]]

 [[208 722]]

 [[209 721]]

 [[209 715]]

 [[207 713]]]
